//! Report export — JSON, Markdown, CSV, TXT, HTML.

use crate::models::{ScanResult, Vulnerability};

// ─── JSON ──────────────────────────────────────────────────────────────────────

pub fn to_json(result: &ScanResult) -> Result<String, String> {
    serde_json::to_string_pretty(result).map_err(|e| e.to_string())
}

// ─── CSV ───────────────────────────────────────────────────────────────────────

pub fn to_csv(result: &ScanResult) -> String {
    let mut out = String::from(
        "ID,Severity,Category,Title,File,Line,CWE,Description,Remediation\n"
    );

    for v in &result.vulnerabilities {
        let row = format!(
            "{},{},{:?},{},{},{},{},{},{}\n",
            csv_escape(&v.id),
            format!("{:?}", v.severity),
            v.category,
            csv_escape(&v.title),
            csv_escape(&v.file_path),
            v.line_number.map(|n| n.to_string()).unwrap_or_default(),
            csv_escape(v.cwe_id.as_deref().unwrap_or("")),
            csv_escape(&v.description),
            csv_escape(&v.remediation),
        );
        out.push_str(&row);
    }

    out
}

fn csv_escape(s: &str) -> String {
    if s.contains(',') || s.contains('"') || s.contains('\n') {
        format!("\"{}\"", s.replace('"', "\"\""))
    } else {
        s.to_string()
    }
}

// ─── Markdown ─────────────────────────────────────────────────────────────────

pub fn to_markdown(result: &ScanResult) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# SecuScan AI — Security Report\n\n");
    md.push_str(&format!("> **Target:** `{}`\n", result.target_path));
    md.push_str(&format!("> **Scan ID:** `{}`\n", result.scan_id));
    md.push_str(&format!("> **Date:** {}\n", result.started_at.format("%Y-%m-%d %H:%M UTC")));
    if let Some(end) = result.completed_at {
        let duration = (end - result.started_at).num_seconds();
        md.push_str(&format!("> **Duration:** {}s\n", duration));
    }
    md.push_str(&format!(
        "> **Files scanned:** {} / {}\n\n",
        result.scanned_files, result.total_files
    ));

    // Summary
    md.push_str("## Summary\n\n");
    md.push_str("| Severity | Count |\n|----------|-------|\n");
    md.push_str(&format!("| 🔴 Critical | {} |\n", result.stats.critical));
    md.push_str(&format!("| 🟠 High     | {} |\n", result.stats.high));
    md.push_str(&format!("| 🟡 Medium   | {} |\n", result.stats.medium));
    md.push_str(&format!("| 🟢 Low      | {} |\n", result.stats.low));
    md.push_str(&format!("| ℹ️ Info     | {} |\n", result.stats.info));
    md.push_str(&format!("| **Total**   | **{}** |\n\n", result.stats.total()));

    // Findings grouped by severity
    for severity_label in &["Critical", "High", "Medium", "Low", "Info"] {
        let group: Vec<&Vulnerability> = result.vulnerabilities.iter()
            .filter(|v| format!("{:?}", v.severity).to_lowercase() == severity_label.to_lowercase())
            .collect();

        if group.is_empty() { continue; }

        let emoji = match *severity_label {
            "Critical" => "🔴",
            "High"     => "🟠",
            "Medium"   => "🟡",
            "Low"      => "🟢",
            _          => "ℹ️",
        };

        md.push_str(&format!("## {} {} Findings\n\n", emoji, severity_label));

        for (i, v) in group.iter().enumerate() {
            md.push_str(&format!("### {}.{} {}\n\n", severity_label, i + 1, v.title));
            md.push_str(&format!("- **File:** `{}`\n", v.file_path));
            if let Some(line) = v.line_number {
                md.push_str(&format!("- **Line:** {}\n", line));
            }
            if let Some(cwe) = &v.cwe_id {
                md.push_str(&format!("- **CWE:** {}\n", cwe));
            }
            md.push_str(&format!("\n**Description:**\n{}\n\n", v.description));
            md.push_str(&format!("**Remediation:**\n{}\n\n", v.remediation));
            if let Some(snippet) = &v.code_snippet {
                md.push_str("**Code context:**\n```\n");
                md.push_str(snippet);
                md.push_str("\n```\n\n");
            }
            if let Some(fix) = &v.ai_fix {
                md.push_str("**AI-suggested fix:**\n```\n");
                md.push_str(fix);
                md.push_str("\n```\n\n");
            }
            md.push_str("---\n\n");
        }
    }

    // Scan errors
    if !result.errors.is_empty() {
        md.push_str("## ⚠️ Scan Errors\n\n");
        for e in &result.errors {
            md.push_str(&format!("- `{}`: {}\n", e.file_path, e.error));
        }
        md.push('\n');
    }

    md.push_str(&format!("---\n*Generated by SecuScan AI v{}*\n", env!("CARGO_PKG_VERSION")));
    md
}

// ─── Plain Text ───────────────────────────────────────────────────────────────

pub fn to_txt(result: &ScanResult) -> String {
    let mut out = String::new();
    let sep  = "=".repeat(72);
    let sep2 = "-".repeat(72);

    out.push_str("SECUSCAN AI — SECURITY REPORT\n");
    out.push_str(&sep); out.push('\n');
    out.push_str(&format!("Target  : {}\n", result.target_path));
    out.push_str(&format!("Scan ID : {}\n", result.scan_id));
    out.push_str(&format!("Date    : {}\n", result.started_at.format("%Y-%m-%d %H:%M UTC")));
    out.push_str(&format!("Files   : {} / {}\n\n", result.scanned_files, result.total_files));

    out.push_str("SUMMARY\n");
    out.push_str(&sep2); out.push('\n');
    out.push_str(&format!("  Critical : {}\n", result.stats.critical));
    out.push_str(&format!("  High     : {}\n", result.stats.high));
    out.push_str(&format!("  Medium   : {}\n", result.stats.medium));
    out.push_str(&format!("  Low      : {}\n", result.stats.low));
    out.push_str(&format!("  Info     : {}\n", result.stats.info));
    out.push_str(&format!("  TOTAL    : {}\n\n", result.stats.total()));

    out.push_str("FINDINGS\n");
    out.push_str(&sep); out.push('\n');

    for (i, v) in result.vulnerabilities.iter().enumerate() {
        out.push_str(&format!("\n[{:>3}] [{:?}] {}\n", i + 1, v.severity, v.title.to_uppercase()));
        out.push_str(&format!("      File       : {}\n", v.file_path));
        if let Some(l) = v.line_number {
            out.push_str(&format!("      Line       : {}\n", l));
        }
        if let Some(c) = &v.cwe_id {
            out.push_str(&format!("      CWE        : {}\n", c));
        }
        out.push_str(&format!("      Description: {}\n", v.description));
        out.push_str(&format!("      Remediation: {}\n", v.remediation));
        if let Some(fp) = &v.fp_hint {
            out.push_str(&format!("      [FP?]      : {}\n", fp));
        }
        if let Some(snippet) = &v.code_snippet {
            out.push_str("      Code:\n");
            for line in snippet.lines() {
                out.push_str(&format!("        {}\n", line));
            }
        }
        out.push_str(&format!("      {}\n", sep2));
    }

    if !result.errors.is_empty() {
        out.push_str("\nSCAN ERRORS\n");
        out.push_str(&sep2); out.push('\n');
        for e in &result.errors {
            out.push_str(&format!("  {} : {}\n", e.file_path, e.error));
        }
    }

    out.push_str(&format!("\nGenerated by SecuScan AI v{}\n", env!("CARGO_PKG_VERSION")));
    out
}

// ─── HTML ─────────────────────────────────────────────────────────────────────

const HTML_CSS: &str = r#"<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,sans-serif;background:#f5f5f5;color:#222;font-size:14px}
header{background:#0a0d14;color:#fff;padding:20px 32px;display:flex;align-items:center;gap:12px}
header h1{font-size:20px;font-weight:700}header span{color:#00d4ff;font-size:13px}
.meta{background:#fff;border-bottom:1px solid #e0e0e0;padding:12px 32px;font-size:13px;color:#555}
.summary{display:flex;gap:12px;padding:20px 32px;flex-wrap:wrap}
.stat{background:#fff;border-radius:8px;padding:12px 20px;text-align:center;min-width:90px;border:1px solid #e0e0e0}
.stat .n{font-size:28px;font-weight:700}.stat .l{font-size:12px;color:#888;margin-top:2px}
.stat.critical .n{color:#e53935}.stat.high .n{color:#f57c00}
.stat.medium .n{color:#f9a825}.stat.low .n{color:#43a047}.stat.info .n{color:#1e88e5}
table{width:calc(100% - 64px);margin:0 32px 32px;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e0e0e0}
th{background:#f0f0f0;padding:10px 14px;text-align:left;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.05em}
tr.finding{cursor:pointer}tr.finding:hover{background:#fafafa}
td{padding:10px 14px;border-bottom:1px solid #f0f0f0;vertical-align:middle}
.num{color:#aaa;width:40px;text-align:center}
.badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;color:#fff}
.badge.critical{background:#e53935}.badge.high{background:#f57c00}
.badge.medium{background:#f9a825;color:#222}.badge.low{background:#43a047}.badge.info{background:#1e88e5}
.cwe{font-size:11px;color:#888;margin-left:6px}
.filepath{font-family:monospace;font-size:12px;color:#555}
tr.detail{background:#fafff0}tr.detail.hidden{display:none}
tr.detail td{padding:14px 14px 14px 68px;border-bottom:2px solid #e8e8e8}
tr.detail p{margin-bottom:8px;line-height:1.5}
.snippet{background:#1e1e1e;color:#d4d4d4;padding:12px;border-radius:6px;font-size:12px;overflow-x:auto;margin-top:8px;white-space:pre}
.fp-hint{background:#fff8e1;border-left:3px solid #f9a825;padding:8px 12px;margin:8px 0;font-size:12px;border-radius:0 4px 4px 0}
footer{text-align:center;color:#aaa;font-size:12px;padding:20px;margin-top:20px}
</style>"#;

pub fn to_html(result: &ScanResult) -> String {
    let date    = result.started_at.format("%Y-%m-%d %H:%M UTC").to_string();
    let stats   = &result.stats;
    let ver     = env!("CARGO_PKG_VERSION");

    // Build rows
    let mut rows = String::new();
    for (i, v) in result.vulnerabilities.iter().enumerate() {
        let sev_class = format!("{:?}", v.severity).to_lowercase();
        let sev_label = format!("{:?}", v.severity).to_uppercase();
        let snippet_html = v.code_snippet.as_deref()
            .map(|s| format!("<pre class=\"snippet\">{}</pre>", html_escape(s)))
            .unwrap_or_default();
        let fp_html = v.fp_hint.as_deref()
            .map(|h| format!(
                "<div class=\"fp-hint\">\u{26a0}\u{fe0f} Possible faux positif \u{2014} {}</div>",
                html_escape(h)
            ))
            .unwrap_or_default();
        let line_str = v.line_number.map(|l| format!(":{l}")).unwrap_or_default();
        let cwe_str  = v.cwe_id.as_deref()
            .map(|c| format!(" <span class=\"cwe\">{}</span>", c))
            .unwrap_or_default();

        rows.push_str("<tr class=\"finding ");
        rows.push_str(&sev_class);
        rows.push_str("\" onclick=\"this.nextElementSibling.classList.toggle('hidden')\">");
        rows.push_str(&format!("<td class=\"num\">{}</td>", i + 1));
        rows.push_str(&format!("<td><span class=\"badge {}\">{}</span></td>", sev_class, sev_label));
        rows.push_str(&format!("<td>{}{}</td>", html_escape(&v.title), cwe_str));
        rows.push_str(&format!("<td class=\"filepath\">{}{}</td>", html_escape(&v.file_path), line_str));
        rows.push_str("</tr>\n");
        rows.push_str("<tr class=\"detail hidden\"><td colspan=\"4\">");
        rows.push_str(&format!("<p>{}</p>", html_escape(&v.description)));
        rows.push_str(&format!("<p><strong>Remediation:</strong> {}</p>", html_escape(&v.remediation)));
        rows.push_str(&fp_html);
        rows.push_str(&snippet_html);
        rows.push_str("</td></tr>\n");
    }

    // Assemble full document (no CSS inside format! — avoids brace escaping hell)
    let mut html = String::with_capacity(rows.len() + 8192);
    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("<meta charset=\"UTF-8\"/>\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/>\n");
    html.push_str(&format!("<title>SecuScan AI Report \u{2014} {date}</title>\n"));
    html.push_str(HTML_CSS);
    html.push_str("\n</head>\n<body>\n");
    // Header
    html.push_str("<header>\n");
    html.push_str("  <svg width=\"28\" height=\"28\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#00d4ff\" stroke-width=\"2\">\n");
    html.push_str("    <path d=\"M12 2L3 7v5c0 5.25 3.75 10.15 9 11.35C17.25 22.15 21 17.25 21 12V7L12 2z\"/>\n");
    html.push_str("    <path d=\"M9 12l2 2 4-4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n");
    html.push_str("  </svg>\n");
    html.push_str("  <h1>SecuScan AI <span>Security Report</span></h1>\n</header>\n");
    // Meta bar
    html.push_str(&format!(
        "<div class=\"meta\">Target: <strong>{}</strong> &nbsp;|&nbsp; Date: <strong>{date}</strong> &nbsp;|&nbsp; Files: <strong>{}/{}</strong> &nbsp;|&nbsp; Scan ID: <code>{}</code></div>\n",
        html_escape(&result.target_path), result.scanned_files, result.total_files, html_escape(&result.scan_id)
    ));
    // Stats
    html.push_str("<div class=\"summary\">\n");
    for (cls, label, n) in [
        ("critical", "Critical", stats.critical),
        ("high",     "High",     stats.high),
        ("medium",   "Medium",   stats.medium),
        ("low",      "Low",      stats.low),
        ("info",     "Info",     stats.info),
    ] {
        html.push_str(&format!(
            "  <div class=\"stat {cls}\"><div class=\"n\">{n}</div><div class=\"l\">{label}</div></div>\n"
        ));
    }
    html.push_str(&format!(
        "  <div class=\"stat\"><div class=\"n\">{}</div><div class=\"l\">Total</div></div>\n",
        stats.total()
    ));
    html.push_str("</div>\n");
    // Table
    html.push_str("<table>\n<thead><tr><th>#</th><th>Severity</th><th>Finding</th><th>File</th></tr></thead>\n<tbody>\n");
    html.push_str(&rows);
    html.push_str("</tbody>\n</table>\n");
    html.push_str(&format!(
        "<footer>Generated by SecuScan AI v{ver} \u{2014} Click a row to expand details</footer>\n"
    ));
    html.push_str("</body>\n</html>");
    html
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
     .replace('<', "&lt;")
     .replace('>', "&gt;")
     .replace('"', "&quot;")
}
