//! Report export — JSON, Markdown, CSV.

use crate::models::{ScanResult, Vulnerability};

// ─── JSON ──────────────────────────────────────────────────────────────────────

pub fn to_json(result: &ScanResult) -> Result<String, String> {
    serde_json::to_string_pretty(result).map_err(|e| e.to_string())
}

// ─── CSV ───────────────────────────────────────────────────────────────────────

pub fn to_csv(result: &ScanResult) -> String {
    let mut out = String::from(
        "ID,Severity,Category,Title,File,Line,CWE,Description,Remediation\n"
    );

    for v in &result.vulnerabilities {
        let row = format!(
            "{},{},{:?},{},{},{},{},{},{}\n",
            csv_escape(&v.id),
            format!("{:?}", v.severity),
            v.category,
            csv_escape(&v.title),
            csv_escape(&v.file_path),
            v.line_number.map(|n| n.to_string()).unwrap_or_default(),
            csv_escape(v.cwe_id.as_deref().unwrap_or("")),
            csv_escape(&v.description),
            csv_escape(&v.remediation),
        );
        out.push_str(&row);
    }

    out
}

fn csv_escape(s: &str) -> String {
    if s.contains(',') || s.contains('"') || s.contains('\n') {
        format!("\"{}\"", s.replace('"', "\"\""))
    } else {
        s.to_string()
    }
}

// ─── Markdown ─────────────────────────────────────────────────────────────────

pub fn to_markdown(result: &ScanResult) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# SecuScan AI — Security Report\n\n");
    md.push_str(&format!("> **Target:** `{}`\n", result.target_path));
    md.push_str(&format!("> **Scan ID:** `{}`\n", result.scan_id));
    md.push_str(&format!("> **Date:** {}\n", result.started_at.format("%Y-%m-%d %H:%M UTC")));
    if let Some(end) = result.completed_at {
        let duration = (end - result.started_at).num_seconds();
        md.push_str(&format!("> **Duration:** {}s\n", duration));
    }
    md.push_str(&format!(
        "> **Files scanned:** {} / {}\n\n",
        result.scanned_files, result.total_files
    ));

    // Summary
    md.push_str("## Summary\n\n");
    md.push_str("| Severity | Count |\n|----------|-------|\n");
    md.push_str(&format!("| 🔴 Critical | {} |\n", result.stats.critical));
    md.push_str(&format!("| 🟠 High     | {} |\n", result.stats.high));
    md.push_str(&format!("| 🟡 Medium   | {} |\n", result.stats.medium));
    md.push_str(&format!("| 🟢 Low      | {} |\n", result.stats.low));
    md.push_str(&format!("| ℹ️ Info     | {} |\n", result.stats.info));
    md.push_str(&format!("| **Total**   | **{}** |\n\n", result.stats.total()));

    // Findings grouped by severity
    for severity_label in &["Critical", "High", "Medium", "Low", "Info"] {
        let group: Vec<&Vulnerability> = result.vulnerabilities.iter()
            .filter(|v| format!("{:?}", v.severity).to_lowercase() == severity_label.to_lowercase())
            .collect();

        if group.is_empty() { continue; }

        let emoji = match *severity_label {
            "Critical" => "🔴",
            "High"     => "🟠",
            "Medium"   => "🟡",
            "Low"      => "🟢",
            _          => "ℹ️",
        };

        md.push_str(&format!("## {} {} Findings\n\n", emoji, severity_label));

        for (i, v) in group.iter().enumerate() {
            md.push_str(&format!("### {}.{} {}\n\n", severity_label, i + 1, v.title));
            md.push_str(&format!("- **File:** `{}`\n", v.file_path));
            if let Some(line) = v.line_number {
                md.push_str(&format!("- **Line:** {}\n", line));
            }
            if let Some(cwe) = &v.cwe_id {
                md.push_str(&format!("- **CWE:** {}\n", cwe));
            }
            md.push_str(&format!("\n**Description:**\n{}\n\n", v.description));
            md.push_str(&format!("**Remediation:**\n{}\n\n", v.remediation));
            if let Some(snippet) = &v.code_snippet {
                md.push_str("**Code context:**\n```\n");
                md.push_str(snippet);
                md.push_str("\n```\n\n");
            }
            if let Some(fix) = &v.ai_fix {
                md.push_str("**AI-suggested fix:**\n```\n");
                md.push_str(fix);
                md.push_str("\n```\n\n");
            }
            md.push_str("---\n\n");
        }
    }

    // Scan errors
    if !result.errors.is_empty() {
        md.push_str("## ⚠️ Scan Errors\n\n");
        for e in &result.errors {
            md.push_str(&format!("- `{}`: {}\n", e.file_path, e.error));
        }
        md.push('\n');
    }

    md.push_str("---\n*Generated by SecuScan AI v1.0.0*\n");
    md
}
